@QLN.DataMigration_HostAddress = http://localhost:5084

###
GET {{QLN.DataMigration_HostAddress}}/migrate_categories?environment=dev
Accept: application/json

###
GET {{QLN.DataMigration_HostAddress}}/migrate_items?environment=prod&category_id=7216 // &sort_field=price&sort_order=desc&page_size=30&page=1
Accept: application/json

### Migrate Categories
POST http://ql-migrate.westeurope.cloudapp.azure.com/qlnext-v2/items-categories.php
Content-Type: application/x-www-form-urlencoded

env=dev

### Migrate Ads
POST http://ql-migrate.westeurope.cloudapp.azure.com/qlnext-v2/items.php
Content-Type: application/x-www-form-urlencoded

env=dev
&category_id=7216
&sort_field=price
&sort_order=desc
&keywords=wardrobes
&page_size=30
&page=1

### Migrate News
GET https://www.qatarliving.com/qlnapi/articles?page=1&page_size=10&forum_id=20000040
Content-Type: application/json

### Migrate Events
GET https://test.qatarliving.com/qlnapi/events?page=1&page_size=10
Content-Type: application/json

### Migrate community
GET https://test.qatarliving.com/qlnapi/community?page=1&page_size=10
Content-Type: application/json
