trigger:
  branches:
    include:
    - qln-dev
  paths:
    include:
    - './QLN.Blazor.Base/**'
    - './QLN.Common/**'
    - './QLN.Web.Shared/**'

variables:
 - name: acrRegistry
   value: qlnv2-ezftf8ehejdadpfn

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureContainerApps@1
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)'
    appSourcePath: '$(Build.SourcesDirectory)/QLN.Blazor.Base'
    dockerfilePath: '$(Build.SourcesDirectory)/QLN.Blazor.Base/Dockerfile'
    azureSubscription: 'dev-qlnext'
    acrName: $(acrRegistry)
    acrUsername: 'qlnv2'
    acrPassword: 'jxmPri2GCql4OHO5Fl+3C0Bii3fmUbsrEZ1EHDbx/y+ACRDo/bQ0'
    imageToBuild: 'qlnv2-ezftf8ehejdadpfn.azurecr.io/qlnv2/blazorbase:$(Build.BuildId).$(Build.BuildNumber)'
    containerAppName: 'capp-blazorbase'
    resourceGroup: 'rg-containerapps-dev'
    runtimeStack: 'dotnetcore:8.0'