// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QLN.Common.Infrastructure.QLDbContext;

#nullable disable

namespace QLN.Common.Migrations.QLSubscription
{
    [DbContext(typeof(QLSubscriptionContext))]
    [Migration("20250807085010_Subscription")]
    partial class Subscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QLN.Common.Infrastructure.Model.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentVertical")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Vertical")
                        .HasColumnType("integer");

                    b.HasKey("ProductCode");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("Vertical");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("QLN.Common.Infrastructure.Model.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Vertical")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductCode");

                    b.HasIndex("UserId");

                    b.HasIndex("Vertical");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("QLN.Common.Infrastructure.Model.UserAddOn", b =>
                {
                    b.Property<Guid>("UserAddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Vertical")
                        .HasColumnType("integer");

                    b.HasKey("UserAddOnId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductCode");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.HasIndex("Vertical");

                    b.ToTable("UserAddOns");
                });

            modelBuilder.Entity("QLN.Common.Infrastructure.Model.Product", b =>
                {
                    b.OwnsOne("QLN.Common.Infrastructure.Model.Product.Constraints#Dictionary", "Constraints", b1 =>
                        {
                            b1.Property<string>("ProductCode")
                                .HasColumnType("character varying(30)");

                            b1.HasKey("ProductCode");

                            b1.ToTable("Products");

                            b1.ToJson("Constraints");

                            b1.WithOwner()
                                .HasForeignKey("ProductCode");
                        });

                    b.Navigation("Constraints")
                        .IsRequired();
                });

            modelBuilder.Entity("QLN.Common.Infrastructure.Model.Subscription", b =>
                {
                    b.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "Quota", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.ToJson("Quota");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("Quota")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
