@QLN.Backend.API_HostAddress = https://localhost:7161

@DrupalQueue = qln_news_news_qatar

GET {{QLN.Backend.API_HostAddress}}/api/content/{{DrupalQueue}}/landing
Accept: application/json


###

@QLN.Drupal.API_HostAddress = https://test.qatarliving.com

GET {{QLN.Drupal.API_HostAddress}}/qlnapi/landing/qln_contents_daily
Accept: application/json

###
GET {{QLN.Drupal.API_HostAddress}}/qlnapi/node?slug=forum/news/akram-afif-scores-twice-qatar-beat-lebanon-afc-asian-cup-opener
Accept: application/json

###
GET {{QLN.Drupal.API_HostAddress}}/qlnapi/node?slug=events/fifa-arab-cup-qatar-2021
Accept: application/json
