@QLN.Backend.API_HostAddress = https://localhost:7161

@DrupalQueue = qln_news_news_middle_east

GET {{QLN.Backend.API_HostAddress}}/api/content/{{DrupalQueue}}/landing
Accept: application/json

###
GET {{QLN.Backend.API_HostAddress}}/api/content/event/events/fifa-arab-cup-qatar-2021
Accept: application/json

###
GET {{QLN.Backend.API_HostAddress}}/api/content/post/forum/news/akram-afif-scores-twice-qatar-beat-lebanon-afc-asian-cup-opener
Accept: application/json

###
GET {{QLN.Backend.API_HostAddress}}/api/content/news/forum/news/akram-afif-scores-twice-qatar-beat-lebanon-afc-asian-cup-opener
Accept: application/json

###

GET {{QLN.Backend.API_HostAddress}}/api/content/events
Accept: application/json

###

GET {{QLN.Backend.API_HostAddress}}/api/content/categories
Accept: application/json

###
GET {{QLN.Backend.API_HostAddress}}/api/content/community?forum_id=20000006
Accept: application/json

###
POST {{QLN.Backend.API_HostAddress}}/api/content/comment/save
Accept: application/json
Content-Type: application/json
{
  "nid": 46438698,
  "uid": 5834086,
  "comment": "Great article! 3"
}

###
POST {{QLN.Backend.API_HostAddress}}/api/content/post/save
Accept: application/json
Content-Type: application/json
{
  "type": "post",
  "forum_id": 20000006,
  "uid": 5834086,
  "title": "Posted from Crayon",
  "description": "This is description"
}


###################################

@QLN.Drupal.API_HostAddress = https://test.qatarliving.com

GET {{QLN.Drupal.API_HostAddress}}/qlnapi/categories
Accept: application/json

###

GET {{QLN.Drupal.API_HostAddress}}/qlnapi/events
Accept: application/json

###
GET {{QLN.Drupal.API_HostAddress}}/qlnapi/landing/{{DrupalQueue}}
Accept: application/json

###
GET {{QLN.Drupal.API_HostAddress}}/qlnapi/node?slug=forum/news/akram-afif-scores-twice-qatar-beat-lebanon-afc-asian-cup-opener
Accept: application/json

###
GET {{QLN.Drupal.API_HostAddress}}/qlnapi/node?slug=events/fifa-arab-cup-qatar-2021
Accept: application/json

###
GET {{QLN.Drupal.API_HostAddress}}/qlnapi/community?page=1&page_size=10&order=asc&forum_id=20000006
Accept: application/json

###
POST {{QLN.Drupal.API_HostAddress}}/qlnapi/comment/save
Accept: application/json
Content-Type: application/json
{
  "nid": 46438698,
  "uid": 5834086,
  "comment": "Great article! 3"
}

###
POST {{QLN.Drupal.API_HostAddress}}/qlnapi/node/save
Accept: application/json
Content-Type: application/json
{
  "type": "post",
  "forum_id": 20000006,
  "uid": 5834086,
  "title": "Posted from Crayon",
  "description": "This is description"
}