apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bannerimagestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStoreId
    value: "true"
  - name: enableQuery
    value: "true"