apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: contentstatestore    
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379        # Your Redis server address
    - name: redisPassword
      value: ""                   # If no password, keep empty
    - name: enableQuery
      value: "true"
    - name: keyPrefix
      value: "name"